plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Name
    seperator: '_'
    prefix: tag
  - prefix: instance_type
    key: instance_type

compose:
  ansible_host: public_ip_address
  foo: private_ip_address
  boo: instance_id
  key: key_name

filters:
  instance-state-name : running
  tag:env :ansible               #Console dan ec2 lara tag (ansible) atadik



#  $ ansible-inventory --graph   outputlari kullanrak ping atilabilir
#  $ ansible instance_type_t2_micro -m ping